name: PR

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn tsc
      - run: yarn lint
      - run: yarn test
      - uses: codecov/codecov-action@v1

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - uses: superdispatch/actions/build-size/limit@v1
        with:
          install_command: 'yarn install'
          build_command: 'yarn build'
