name: PR

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          pnpm-version: 10
      - run: pnpm tsc
      - run: pnpm lint
      - run: pnpm test
      - uses: codecov/codecov-action@v2
      - uses: EndBug/add-and-commit@v7
        if: ${{ failure() && github.actor == 'renovate' }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          pnpm-version: 10
      - uses: superdispatch/actions/build-size/limit@v2
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        with:
          install_command: 'pnpm install'
          build_command: 'pnpm build'
